spring:
  application:
    name: extracted-backend
  data:
    mongodb:
      uri: "mongodb+srv://sawandmagedaragama_db_user:12126441rentacar@cluster0.cd2xx6j.mongodb.net/car-rental-db?appName=Cluster0&retryWrites=true&w=majority"
      auto-index-creation: true

server:
  port: 8080

logging:
  level:
    root: INFO
    com.example.backend: DEBUG
